org: joebot
app: calmap
service: calmap

provider:
  name: aws
  region: us-west-1
  runtime: provided.al2
  architecture: arm64

  deploymentBucket:
    name: calmap-deploy-${sls:stage}

  httpApi:
    cors: true
    name: ${self:service}-${sls:stage}

  logs:
    httpApi: true

package:
  individually: true

functions:
  ping:
    name: ping-${sls:stage}
    handler: bootstrap
    package:
      artifact: build/lambda/ping.zip
    events:
      - http:
          path: /ping
          method: get
