version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - npm install
  build:
    commands:
      - sls deploy --stage dev --verbose
artifacts:
  files:
    - '**/*'