version: 0.2
env:
  parameter-store:
    SERVERLESS_ACCESS_KEY: "/CodeBuild/SERVERLESS_ACCESS_KEY"
phases:
  install:
    runtime-versions:
      nodejs: latest
      golang: 1.24
    commands:
      - npm i -g serverless
      - npm install
      - serverless deploy --stage dev --verbose
artifacts:
  files:
    - '**/*'